//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCxC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Balance
    {
        public int Id_balance { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DisplayName("Id del cliente")]
        public int Id_cliente { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DisplayName("Fecha de corte")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_corte { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DisplayName("Antiguedad promedio (Saldos)")]
        public int Antiguedad_promedio_saldos { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
  
        public decimal Monto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
