//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCxC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Balances
    {
        [Display(Name = "No. Balance")]
        public int Id_balance { get; set; }
        [Display(Name = "No. Identificación")]
        public int Id_cliente { get; set; }
        [Display(Name = "Fecha de corte")]
        public System.DateTime Fecha_corte { get; set; }
        [Display(Name = "Antigüedad promedio de saldos")]
        public int Antiguedad_promedio_saldos { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
