//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCxC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        public int Id_balance { get; set; }
        public int Id_cliente { get; set; }
        public System.DateTime Fecha_corte { get; set; }
        public int Antiguedad_promedio_saldos { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
