//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCxC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaccione
    {

       //comentario
        public int Id_transaccion { get; set; }

        [Required(ErrorMessage ="Este campo es obligatorio")]
        [DisplayName("Tipo de movimiento")]
        public string Tipo_movimiento { get; set; }


        [DisplayName("Id tipo de movimiento")]
        
        public int Id_tipoDocumento { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [DisplayName("Numero de documento")]
        public int Numero_documento { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
 
        public System.DateTime Fecha { get; set; }

       
       // [DisplayName("Id del cliente")]
      
        public int Id_cliente { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public decimal Monto { get; set; }

        [DisplayName("Id del cliente")]
        public virtual Cliente Cliente { get; set; }

        [DisplayName("Tipo Documento")]
        public virtual Tipo_Documentos Tipo_Documentos { get; set; }
    }
}
